### ISSUE TITLE
Does not display correctly on Edge for Android

### ISSUE THREAD

**Issue by Rob-Manders** [5t3ph/smolcss#2]
The content is spilling off the page when viewed on the Microsoft Edge browser on Android.

Edge version 46.01.4.5140

![Screenshot_20210226_220026_com microsoft emmx](https://user-images.githubusercontent.com/31056731/109390706-2195d200-790b-11eb-8260-5597b56cc848.jpg)
![Screenshot_20210226_220033_com microsoft emmx](https://user-images.githubusercontent.com/31056731/109390711-2490c280-790b-11eb-9d3a-ef9aa96b2ef4.jpg)

**Comment by 5t3ph** [comment]
@Rob-Manders thanks for letting me know. I made a couple edits based on my best guess of what is happening (guessing there's not support or incomplete support for the `ch` unit, `ex` unit, and the `max()` function, maybe also `calc`). Hope the edits help you!

**Comment by Rob-Manders** [comment]
@5t3ph no change I'm afraid. I'm not too fussed, I can use another browser. I just thought you should be aware of it.

**Comment by 5t3ph** [comment]
@Rob-Manders thanks for following up, sorry to hear it didn't make a difference! It seems to be an extremely infrequent combination according to my analytics. I'm not very familiar with Android so I'm glad to hear you have another option.
