### ISSUE TITLE
Demos can't resize smaller on Safari

### ISSUE THREAD

**Issue by chuckhoupt** [5t3ph/smolcss#4]
Safari doesn't support CSS resizing smaller than the original item size, so the demo divs can't be made smaller than their starting width. This makes it difficult to see the nice scaling/stacking behavior of the demos.

There is a kludgy workaround mentioned in https://stackoverflow.com/a/33858878 , which might be implemented as:

```
.demo:active { width: 0; }
```

However, it has various bad side-effects, so I'm not sure if there is a solution short of using JS to resize...

**Comment by 5t3ph** [comment]
@chuckhoupt yeah it's an unfortunate thing, but I'm not willing to bring in JS to "fix" it and rather consider it a progressive enhancement of the demos themselves. The resize is a "nice to have", while the code snippet itself is the main content for a user to take away. The "Open in CodePen" is also available if a visitor wants to explore the snippet outcome more fully, which would allow full resizing.

Thanks for the workaround link, I had not encountered that in my earlier research! I might try to experiment with that a bit more after I finish some other priorities :)
